name: Validation

on:
  - push
  - pull_request

jobs:
  test:
    name: Test-Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Okysa
      - uses: actions/checkout@v3
        with:
          repository: x4dr/GamePack
          path: GamePack
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version-file: "Okysa/.python-version"
      - name: Install the project
        working-directory: Okysa
        run: uv sync --all-extras --dev
      - name: Run unittests/coverage
        working-directory: Okysa
        run: |
          uv run pytest --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=45
      - name: Coveralls Parallel
        working-directory: Okysa
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-linux-uv
          parallel: true
          file: coverage.xml

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true

  Lint:
    name: Pre-Commit Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Okysa
      - uses: actions/checkout@v3
        with:
          repository: x4dr/GamePack
          path: GamePack
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version-file: "Okysa/.python-version"
      - name: Install dependencies
        working-directory: Okysa
        run: uv sync --all-extras --dev
      - name: Run pre-commit
        working-directory: Okysa
        run: uv run pre-commit run --all-files
